name: Docker Image CI

on:
  push:
    branches: [ master ]


env:
  IMAGE_NAME: grafonnet

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:latest

      - name: Push image to GitHub Container Registry
        run: |
          # Log into GitHub Container Registry
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Change all uppercase to lowercase
          docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest

      - name: Push image to DockerHub Container Registry
        run: |
          # Log into Dockerhub
          echo "${{ secrets.CR_PAT }}" | docker login -u corentinaltepe --password-stdin
          
          # Change all uppercase to lowercase
          docker push corentinaltepe/$IMAGE_NAME:latest
