name: Docker Image CI

on:
  push:
    branches: [ master ]
  
  # Rebuild master every sunday at 2 AM
  schedule:
    - cron: "0 2 * * 0"


env:
  IMAGE_NAME: grafonnet

jobs:

  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME:latest --build-arg grafonnet_version=master

      - name: Push image to GitHub Container Registry
        run: |
          # Log into GitHub Container Registry
          echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Change all uppercase to lowercase
          docker tag $IMAGE_NAME:latest ghcr.io/corentinaltepe/$IMAGE_NAME:latest
          docker push ghcr.io/corentinaltepe/$IMAGE_NAME:latest

      - name: Push image to DockerHub Container Registry
        run: |
          # Log into Dockerhub
          echo "${{ secrets.DOCKER_HUB_RW }}" | docker login -u corentinaltepe --password-stdin
          
          # Change all uppercase to lowercase
          docker tag $IMAGE_NAME:latest corentinaltepe/$IMAGE_NAME:latest
          docker push corentinaltepe/$IMAGE_NAME:latest

      - name: Push Readme to Docker Hub
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: corentinaltepe
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWD }}
          DOCKERHUB_REPOSITORY: corentinaltepe/grafonnet
